USE ONLINE_STORE
GO


CREATE PROCEDURE DocDSSanPham @idDoiTac CHAR(8)
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITED

BEGIN TRAN
	BEGIN TRY
		IF(NOT EXISTS(	SELECT sp.*
						FROM SANPHAM sp, ChiNhanh_HopDong cnhd
						WHERE sp.ChiNhanhID = cnhd.ChinhanhID AND cnhd.DoiTacID=@idDoiTac))
		BEGIN
			PRINT(N'Đối tác chưa có sản phẩm')
			RETURN
		END


		WAITFOR DELAY '0:0:20'
		SELECT sp.*
		FROM SANPHAM sp,  ChiNhanh_HopDong cnhd
		WHERE sp.ChiNhanhID= cnhd.ChinhanhID AND cnhd.DoiTacID=@idDoiTac

	END TRY

	BEGIN CATCH
		PRINT(N'Lỗi hệ thống')
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
GO

CREATE PROCEDURE SuaSanPham @idSanPham CHAR(8), @gia INT
AS
SET TRANSACTION ISOLATION LEVEL READ COMMITED

BEGIN TRAN
	BEGIN TRY
		IF(NOT EXISTS (SELECT * FROM SANPHAM WHERE @idSanPham=ID))
		BEGIN
			PRINT(N'Sản phẩm không tồn tại')
			ROLLBACK TRAN
		END

		UPDATE SANPHAM
		SET Gia=@gia
		WHERE @idSanPham = ID
		PRINT(N'Cập nhật thành công')
	END TRY

	BEGIN CATCH
	END CATCH
COMMIT TRAN