CREATE DATABASE ONLINE_STORE
GO

USE ONLINE_STORE
GO

CREATE TABLE DOITAC(
  ID CHAR(8),
  Ten NVARCHAR(30),
  DaiDien NVARCHAR(8),
  ThanhPho NVARCHAR(24),
  SoChiNhanh INT,
  SLDonHang INT,
  LoaiHang NVARCHAR(20),
  DiaChi NVARCHAR(50),
  SoDienThoai CHAR(10),
  Email CHAR(50)
)

CREATE TABLE HOPDONG (
  DoiTacID CHAR(8),
  TenNguoiDD NVARCHAR(30),
  SoChiNhanhDK INT,
  DiaChi NVARCHAR(50),
  HieuLuc DATETIME
)

CREATE TABLE SANPHAM (
  ID CHAR(8),
  TenSP NVARCHAR(30),
  ChiNhanhID CHAR(8),
  Gia INT
)

CREATE TABLE CHINHANH (
  ID CHAR(8),
  DiaChi NVARCHAR(50)
)

CREATE TABLE KHACHHANG (
  ID CHAR(8),
  HoTen NVARCHAR(50),
  DienThoai CHAR(10),
  DiaChi NVARCHAR(50),
  Email VARCHAR(30)
)

CREATE TABLE DATHANG (
  KhachHangID CHAR(8),
  DoiTacID CHAR(8),
  DonHangID CHAR(8),
)

CREATE TABLE DONHANG (
  ID CHAR(8),
  SanPhamID CHAR(8),
  SoLuong INT,
  HinhThucTT BIT,
  DiaChi NVARCHAR(50)
)
